service:
  name: hoepel-app-auth-service

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(../../secrets.yml):${self:custom.stage}}
  customDomain:
    domainName: ${file(../../domain.yml):${self:custom.stage}}
    basePath: 'auth'
    stage: ${self:custom.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3

  environment:
    DB_HOST: "${self:custom.secrets.DB_HOST}"
    DB_PORT: "${self:custom.secrets.DB_PORT}"
    DB_HTTPS: "${self:custom.secrets.DB_HTTPS}"
    DB_USER: "${self:custom.secrets.DB_USER}"
    DB_PASS: "${self:custom.secrets.DB_PASS}"

    AUTH0_AUDIENCE: "${self:custom.secrets.AUTH0_AUDIENCE}"
    AUTH0_DOMAIN: "${self:custom.secrets.AUTH0_DOMAIN}"
    AUTH0_CLIENT_ID: "${self:custom.secrets.AUTH0_CLIENT_ID}"
    AUTH0_CLIENT_SECRET: "${self:custom.secrets.AUTH0_CLIENT_SECRET}"
    AUTH0_PEM_KEY: "${self:custom.secrets.AUTH0_PEM_KEY}"

functions:
  authorizer:
    handler: handler.authorizer

  getAllUsers:
    handler: handler.getAllUsers
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: user:list

  getUserById:
    handler: handler.getUserById
    events:
      - http:
          path: user/{userId}
          method: get
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: user:list

  getTenantData:
    handler: handler.getTenantData
    events:
      - http:
          path: user/{userId}/{tenant}
          method: get
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: user:list

  putTenantData:
    handler: handler.putTenantData
    events:
      - http:
          path: user/{userId}/{tenant}
          method: put
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: users:put-data

  getAllPermissions:
    handler: handler.getAllPermissions
    events:
      - http:
          path: permissions
          method: get
          cors: true

  getAllRoles:
    handler: handler.getAllRoles
    events:
      - http:
          path: roles
          method: get
          cors: true
