service:
  name: hoepel-app-child-service

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: ${file(../domain.yml):${self:provider.stage}}
    basePath: 'child'
    stage: ${self:provider.stage}
    createRoute53Record: true

  secrets: ${file(../secrets.yml):${self:provider.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3
  
  environment:
    DB_HOST: "${self:custom.secrets.DB_HOST}"
    DB_PORT: "${self:custom.secrets.DB_PORT}"
    DB_HTTPS: "${self:custom.secrets.DB_HTTPS}"
    DB_USER: "${self:custom.secrets.DB_USER}"
    DB_PASS: "${self:custom.secrets.DB_PASS}"
  

functions:
  allChildren:
    handler: children.all
    events:
      - http:
          method: get
          path: /
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
          request:
            parameters:
              querystrings:
                url: true

  findChild:
    handler: children.byId
    events:
      - http:
          method: get
          path: /{id}
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
          request:
            paths:
              id: true

  createChild:
    handler: children.create
    events:
      - http:
          method: post
          path: /
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0

  updateChild:
    handler: children.update
    events:
      - http:
          method: put
          path: /{id}
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0

  deleteChild:
    handler: children.remove
    events:
      - http:
          method: delete
          path: /{id}
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0