service:
  name: hoepel-app-child-attendance-service

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: ${file(../domain.yml):${self:provider.stage}}
    basePath: 'child-attendance'
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
