service:
  name: hoepel-app-contact-person-service

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(../../secrets.yml):${self:custom.stage}}
  customDomain:
    domainName: ${file(../../domain.yml):${self:custom.stage}}
    basePath: 'contact-person'
    stage: ${self:custom.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3
  tags:
    project: hoepel.app
  stackTags:
    project: hoepel.app

  environment:
    DB_HOST: "${self:custom.secrets.DB_HOST}"
    DB_PORT: "${self:custom.secrets.DB_PORT}"
    DB_HTTPS: "${self:custom.secrets.DB_HTTPS}"
    DB_USER: "${self:custom.secrets.DB_USER}"
    DB_PASS: "${self:custom.secrets.DB_PASS}"

    AUTH0_AUDIENCE: "${self:custom.secrets.AUTH0_AUDIENCE}"
    AUTH0_DOMAIN: "${self:custom.secrets.AUTH0_DOMAIN}"
    AUTH0_CLIENT_ID: "${self:custom.secrets.AUTH0_CLIENT_ID}"
    AUTH0_CLIENT_SECRET: "${self:custom.secrets.AUTH0_CLIENT_SECRET}"
    AUTH0_PEM_KEY: "${self:custom.secrets.AUTH0_PEM_KEY}"

functions:
  authorizer:
    handler: handler.authorizer


  allContactPeople:
    handler: handler.all
    events:
      - http:
          method: get
          path: /
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: contactperson:retrieve

  findContactPerson:
    handler: handler.byId
    events:
      - http:
          method: get
          path: /{id}
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: contactperson:retrieve

  createContactPerson:
    handler: handler.create
    events:
      - http:
          method: post
          path: /
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: contactperson:create

  updateContactPerson:
    handler: handler.update
    events:
      - http:
          method: put
          path: /{id}
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: contactperson:update

  deleteContactPerson:
    handler: handler.remove
    events:
      - http:
          method: delete
          path: /{id}
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            permissionNeeded: contactperson:delete
